<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreReportRequest;
use App\Models\UnsafeMedicineReport;

class UnsafeMedicineReportController extends Controller
{
    /**
     * Admin: list all reports, optionally filtered by status.
     */
    public function adminIndex(Request $request)
    {
        $query = UnsafeMedicineReport::latest();

        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        $reports = $query->paginate(15);

        // Badge counts for filter tabs
        $counts = [
            'all'           => UnsafeMedicineReport::count(),
            'pending'       => UnsafeMedicineReport::where('status', 'pending')->count(),
            'investigating' => UnsafeMedicineReport::where('status', 'investigating')->count(),
            'resolved'      => UnsafeMedicineReport::where('status', 'resolved')->count(),
            'rejected'      => UnsafeMedicineReport::where('status', 'rejected')->count(),
        ];

        return view('admin.unsafe_medicine_report.index', compact('reports', 'counts'));
    }

    /**
     * Admin: show full details of a single report.
     */
    public function adminShow($id)
    {
        $report = UnsafeMedicineReport::findOrFail($id);

        return view('admin.unsafe_medicine_report.view', compact('report'));
    }

    /**
     * Admin: update the status and blacklist flag of a report.
     */
    public function updateStatus(Request $request, $id)
    {
        $request->validate([
            'status'         => 'required|in:pending,investigating,resolved,rejected',
            'is_blacklisted' => 'required|boolean',
        ]);

        UnsafeMedicineReport::findOrFail($id)->update([
            'status'         => $request->status,
            'is_blacklisted' => (bool) $request->is_blacklisted,
        ]);

        return redirect()->route('admin.medicine.reports.view', $id)
            ->with('message', 'Report status updated successfully.');
    }

    /**
     * Show the public report submission form.
     */
    public function index(Request $request)
    {
        $query = UnsafeMedicineReport::latest();

        // Status Filter
        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        // Search Keyword (Tracking No, Medicine, Pharmacy)
        if ($request->filled('search')) {
            $search = $request->search;
            $query->where(function($q) use ($search) {
                $q->where('tracking_number', 'LIKE', "%{$search}%")
                  ->orWhere('medicine_name', 'LIKE', "%{$search}%")
                  ->orWhere('pharmacy_name', 'LIKE', "%{$search}%")
                  ->orWhere('district', 'LIKE', "%{$search}%");
            });
        }

        $reports = $query->paginate(12)->withQueryString();

        // Count queries for badge counts
        $counts = [
            'all'           => UnsafeMedicineReport::count(),
            'pending'       => UnsafeMedicineReport::where('status', 'pending')->count(),
            'investigating' => UnsafeMedicineReport::where('status', 'investigating')->count(),
            'resolved'      => UnsafeMedicineReport::where('status', 'resolved')->count(),
            'rejected'      => UnsafeMedicineReport::where('status', 'rejected')->count(),
        ];

        return view('frontend.unsafe_medicine_report.index', compact('reports', 'counts'));
    }

    /**
     * Frontend: show a single report detail for a logged-in user.
     */
    public function userShow($id)
    {
        $report = UnsafeMedicineReport::findOrFail($id);

        return view('frontend.unsafe_medicine_report.view', compact('report'));
    }

    /**
     * Show the public report submission form.
     */
    public function show()
    {
        return view('frontend.unsafe_medicine_report.report_form');
    }

    /**
     * Handle a new unsafe-medicine report submission.
     *
     * - Uploads up to 5 images to public/unsafe_medicine_reports/images/
     * - Saves the report to the database (tracking_number is auto-generated by the Model)
     * - Redirects back with the tracking number so the user can follow up later
     */
    public function store(StoreReportRequest $request)
    {
        // ── 1. Handle image uploads ───────────────────────────────────────────
        $imagePaths = [];

        if ($request->hasFile('images')) {
            $directory = public_path('unsafe_medicine_reports/images');

            // Create the directory if it does not exist yet
            if (!file_exists($directory)) {
                mkdir($directory, 0755, true);
            }

            foreach ($request->file('images') as $image) {
                // Build a collision-safe filename: prefix + timestamp + random int
                $fileName = 'umr-' . date('YmdHis') . '-' . rand(1000, 9999)
                          . '.' . $image->getClientOriginalExtension();

                $image->move($directory, $fileName);

                $imagePaths[] = 'unsafe_medicine_reports/images/' . $fileName;
            }
        }

        // ── 2. Persist the report ─────────────────────────────────────────────
        // tracking_number is auto-generated in UnsafeMedicineReport::boot()
        $report = UnsafeMedicineReport::create([
            'reporter_name'    => $request->reporter_name,
            'reporter_phone'   => $request->reporter_phone,
            'medicine_name'    => $request->medicine_name,
            'batch_number'     => $request->batch_number,
            'pharmacy_name'    => $request->pharmacy_name,
            'pharmacy_address' => $request->pharmacy_address,
            'district'         => $request->district,
            'description'      => $request->description,
            'images'           => !empty($imagePaths) ? $imagePaths : null,
            'video'            => $request->video,
        ]);

        // ── 3. Redirect with the tracking number ──────────────────────────────
        return redirect()->route('unsafe.medicine.report')
            ->with('success', true)
            ->with('tracking_number', $report->tracking_number);
    }
}
